#!/usr/bin/env bash

set -aeuo pipefail

# shellcheck disable=SC2016

ENVSUBST_FORMAT='$SSH_PUBLIC_KEY,$LIMITS_MEMORY'
INCUS_IMAGE=images:ubuntu/24.04/cloud
INCUS_PROJECT=swarmlab
MANAGER_MEMORY_LIMIT=1024MiB
WORKER_MEMORY_LIMIT=2048MiB

usage() {
  echo "Usage: swarmlab COMMAND"
  echo ""
  echo "Commands:"
  echo "  up    Create the swarmlab project"
}

_up() {
  if incus project show "$INCUS_PROJECT" >/dev/null; then
    echo "Project $INCUS_PROJECT already exists"
  else
    incus project create "$INCUS_PROJECT" <./config/project.yml
  fi

  if [ -z "$SSH_PUBLIC_KEY" ]; then
    echo "SSH_PUBLIC_KEY isn't set. It is needed for SSH operations."
    exit 2
  fi

  for i in {1..3}; do
    LIMITS_MEMORY=$MANAGER_MEMORY_LIMIT envsubst $ENVSUBST_FORMAT <./config/vm.yml | incus launch "$INCUS_IMAGE" "manager$i" --vm --project "$INCUS_PROJECT"
    LIMITS_MEMORY=$WORKER_MEMORY_LIMIT envsubst $ENVSUBST_FORMAT <./config/vm.yml | incus launch "$INCUS_IMAGE" "worker$i" --vm --project "$INCUS_PROJECT"
  done
}

_ps() {
  incus ls --project "$INCUS_PROJECT" -c ns4
}

main() {
  if [ $# -eq 0 ]; then
    usage && exit 1
  fi

  case "$1" in
  "up") _up ;;
  "ps") _ps ;;
  *) usage ;;
  esac
}

main "$@"
