#!/usr/bin/env bash

set -aeuo pipefail

MANAGER_MEMORY_LIMIT=1024MiB
WORKER_MEMORY_LIMIT=2048MiB
# shellcheck disable=SC2016
ENVSUBST_FORMAT='$SSH_PUBLIC_KEY,$LIMITS_MEMORY'

usage() {
  echo "Usage: swarmlab COMMAND"
  echo ""
  echo "Commands:"
  echo "  up    Create the swarmlab project"
}

_up() {
  if incus project show swarmlab >/dev/null; then
    echo "Project swarmlab already exists"
  else
    incus project create swarmlab <./config/project.yml
  fi

  if [ -z "$SSH_PUBLIC_KEY" ]; then
    echo "SSH_PUBLIC_KEY isn't set. It is needed for SSH operations."
    exit 2
  fi

  for i in {1..3}; do
    SSH_PUBLIC_KEY=$SSH_PUBLIC_KEY LIMITS_MEMORY=$MANAGER_MEMORY_LIMIT envsubst $ENVSUBST_FORMAT <./config/vm.yml
    echo "$i"
  done

}

main() {
  if [ $# -eq 0 ]; then
    usage && exit 1
  fi

  case "$1" in
  "up")
    echo "Calling up subcommand"
    _up
    ;;
  *)
    usage
    ;;
  esac
}

main "$@"
